### ISSUE TITLE
Rule Creation

### ISSUE THREAD

**Issue by frankydp** [barneycg/temars-eve-api#11]
Could anyone provide some insight into rule creation.  

Relationship between Main and Additional?
When/how do rule checks happen.?
Bulk manual creation?

Or simply a screenshot of some well organized rules.

**Comment by carmopereira** [comment]
It depends on what you want to do for groups... 
give me more detail on:
1. is for corp/alliance/coallition
2. what groups do you want to read from api?

for example,
A CORP playground:
main group: 
IF "corp" = mycorp THEN assign group CORPORATION
aditional:
IF "CORP CEO" THEN assign group CEO
IF "ROLE DIRECTOR" THEN assign group DIRECTOR

You must check the checkboxes at top for rules to check. and they will be check as the cron runs. so you need to place your cron jobs.

On a forum management perspective, a user should only have a Primary Group and then Additionals.

**Comment by barneycg** [comment]
pretty much what he said ... it is fairly simple.

Main rules are processed in id number order and their processing stops as soon as a match is found, while all additional group rules are processed regardless of how many match.

Only thing to add ... DON'T make a rule that says "If ROLE DIRECTOR then assign group X" ... you would put every director in eve who entered an api key into that group.  You are far better doing "If ROLE DIRECTOR AND CORP = X then assign group Y"

**Comment by frankydp** [comment]
Thanks for the responses.  

My actual issue is that skill based additional rules are not triggering, while other such as director are triggering.
I have tried text names and ids.  The APIs i am using on the test characters are full.
I get no errors on adding the rule but none of the additional rules for skills show up in the check.  

Also if i try to add a second condition to an ID the forms ajax?! does not update the form when switching the type.

**Comment by barneycg** [comment]
you are not running the latest version ... download it from the link in the eve-online forum thread ... I've not updated this repo yet.

**Comment by frankydp** [comment]
Well that settles that. Thanks.  Only feel half stupid now.

**Comment by frankydp** [comment]
Also I am going to do some beautification on the admin pages, are you open to pull request?

Also adding an openfire check.
